"""Helper script to write the investigation_agent.py file."""
import os

TARGET = "/Users/babypegasus/Desktop/prototypes/Scam-likely/scam-likely-hub/app/services/investigation_agent.py"

CONTENT = '''\
"""
Fraud Investigation Agent - LangGraph pipeline.

Generated by +12 Monkeys, adapted for Scam Likely Hub integration.

Pipeline: forensic_analyst -> risk_scorer -> report_generator
Each node uses Claude to produce domain-specific analysis.
"""

import logging
import operator
import os
from typing import Annotated, Any, Dict, List, Optional, TypedDict

from langchain_anthropic import ChatAnthropic
from langgraph.graph import END, StateGraph

logger = logging.getLogger(__name__)


class InvestigationState(TypedDict):
    input: str
    forensic_analyst_output: Annotated[str, operator.add]
    risk_scorer_output: Annotated[str, operator.add]
    report_generator_output: Annotated[str, operator.add]
    final_output: str


def _build_llm() -> ChatAnthropic:
    return ChatAnthropic(
        model=os.getenv("LLM_MODEL", "claude-sonnet-4-20250514"),
        anthropic_api_key=os.getenv("ANTHROPIC_API_KEY"),
    )
'''

if os.path.exists(TARGET):
    os.remove(TARGET)
with open(TARGET, "w") as f:
    f.write(CONTENT)
print(f"Part 1 written: {len(CONTENT.splitlines())} lines")

