import Link from "next/link";

export const metadata = {
  title: "Terms of Service | +12 Monkeys",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#030303] text-zinc-400 px-6 py-20">
      <div className="max-w-2xl mx-auto space-y-8">
        <Link href="/" className="text-[10px] font-mono uppercase tracking-widest text-zinc-600 hover:text-zinc-400">
          ← Back
        </Link>
        <h1 className="text-2xl font-light text-zinc-200">Terms of Service</h1>
        <p className="text-[10px] font-mono text-zinc-600 uppercase tracking-widest">
          Effective: March 1, 2026
        </p>

        <section className="space-y-4 text-sm leading-relaxed">
          <h2 className="text-zinc-300 font-medium">1. Acceptance</h2>
          <p>By accessing or using +12 Monkeys (&quot;the Service&quot;), operated by DeepTech AI (&quot;we&quot;, &quot;us&quot;), you agree to these Terms of Service. If you do not agree, do not use the Service.</p>

          <h2 className="text-zinc-300 font-medium">2. Description of Service</h2>
          <p>+12 Monkeys is an AI-powered platform that helps users design and generate custom AI agent code packages. The Service is provided &quot;as is&quot; and may be updated, modified, or discontinued at any time.</p>

          <h2 className="text-zinc-300 font-medium">3. Accounts &amp; Authentication</h2>
          <p>You authenticate via email magic link. You are responsible for maintaining the security of your email account. You must provide a valid email address and accurate information.</p>

          <h2 className="text-zinc-300 font-medium">4. Free Tier &amp; Paid Plans</h2>
          <p>The Service offers a limited free tier (10 uses). Paid options include:</p>
          <ul className="list-disc list-inside space-y-1 text-zinc-500">
            <li><strong className="text-zinc-400">Pro Plan:</strong> $10/year — unlimited usage</li>
            <li><strong className="text-zinc-400">Single Use:</strong> $1 per additional interaction</li>
          </ul>
          <p>All prices are in USD. Payments are processed securely through Stripe.</p>

          <h2 className="text-zinc-300 font-medium">5. Billing &amp; Refunds</h2>
          <p>Pro subscriptions are billed annually and auto-renew unless cancelled. You may cancel at any time through the Manage Subscription portal. Refunds are handled on a case-by-case basis — contact support within 14 days of purchase. Single-use purchases are non-refundable once the interaction has been consumed.</p>

          <h2 className="text-zinc-300 font-medium">6. Acceptable Use</h2>
          <p>You agree not to: abuse the Service, attempt to bypass usage limits, use the Service for illegal purposes, reverse-engineer the platform, or interfere with its operation.</p>

          <h2 className="text-zinc-300 font-medium">7. Intellectual Property</h2>
          <p>Code generated by the Service is yours to use. The Service itself, including its design, branding, and underlying technology, remains our intellectual property.</p>

          <h2 className="text-zinc-300 font-medium">8. Limitation of Liability</h2>
          <p>The Service is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from use of the Service or generated code. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.</p>

          <h2 className="text-zinc-300 font-medium">9. Termination</h2>
          <p>We may suspend or terminate your access for violation of these terms. You may stop using the Service at any time.</p>

          <h2 className="text-zinc-300 font-medium">10. Changes to Terms</h2>
          <p>We may update these terms. Continued use after changes constitutes acceptance. Material changes will be communicated via email.</p>

          <h2 className="text-zinc-300 font-medium">11. Contact</h2>
          <p>Questions? Email <a href="mailto:1deeptechnology@gmail.com" className="text-zinc-300 underline">1deeptechnology@gmail.com</a></p>
        </section>

        <div className="pt-8 border-t border-zinc-900 text-[9px] font-mono text-zinc-700 uppercase tracking-widest">
          +12 Monkeys © 2025. All Rights Reserved.
        </div>
      </div>
    </div>
  );
}

